version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-demo-xray"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-31392rxojqwi"
s3_prefix = "sam-demo-xray"
region = "ap-northeast-1"
profile = "devserverless"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "SQSQUEUE=\"DemoXRayQueue\" DDBTABLE=\"DemoXRayTable\""
